version: "3"

services:
  postgres:
    image: postgres:12.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: message
      POSTGRES_PASSWORD: message
      POSTGRES_DB: postgres
    restart: always